### ISSUE TITLE
Set RSS3-specific `link` tags

### ISSUE THREAD

**Issue by kecrily** [RSS3-Network/RSS3-Protocol#23]
The <link> tag, which points to a link to an rss file, is an integral part of the RSS ecosystem, which helps people find the rss file for that content.

They look like this

- `<link rel="alternate" type="application/rss+xml" title="Percy » RSS 2.0" href="/feed/">`
- `<link rel="alternate" type="application/rdf+xml" title="Percy » RSS 1.0" href="/feed/rss/">`
- `<link rel="alternate" type="application/atom+xml" title="Percy » ATOM 1.0" href="/feed/atom/">`

RSS3 is currently lacking a standard for this.

Maybe they can look like this

`<link rel="alternate" type="application/rss3+json" title="Percy » RSS3" href="https://rss3.io/kecrily">`

We need to be able to find that content on RSS3 from the site.

**Comment by chilohwei** [comment]
great idea!  I agree it

**Comment by linlinzzo** [comment]
Agree!

**Comment by EdwardWason** [comment]
不能同意的更多

**Comment by linlinzzo** [comment]
> 不能同意的更多

只是添加一个标记而已，方便找到 RSS 3。有什么不同意的地方呢？

**Comment by EdwardWason** [comment]
> > 不能同意的更多
> 
> 只是添加一个标记而已，方便找到 RSS 3。有什么不同意的地方呢？

对不起，气氛组主要任务就是活跃气氛的
难道你也是这个组的？
